### ISSUE TITLE
Replicate AI Icons Not Loading

### ISSUE THREAD

**Issue by snipeor** [SawyerHood/windows9x#12]
## Problem
Replicate AI icons are not loading properly on the client side, despite being successfully generated on the server side.

## Error Message
Console error in app-index.js:33:
```
Image is missing required "src" property:
<img alt="PaintPro.exe" width="24" height="24" decoding="async" data-nimg="1" src style>
```

## Details
- Icons are generated successfully on the server side when a new program is created as I was able to grab the link from the server console and check it manually.
- Client-side browser fails to display the icons
- Error suggests the "src" attribute is missing from the img tag

## Environment
Ubuntu VM Running as localhost
.env with new local mode set to true
.env with api keys set up correctly

Also thanks for setting up a local mode, and appreciate this isn't the main priority right now, looking forward to your public launch!

**Comment by SawyerHood** [comment]
Thanks for the report @snipeor! I just pushed a fix for this!
