### ISSUE TITLE
Code/LLM Dev Output Getting Displayed in IFrame

### ISSUE THREAD

**Issue by snipeor** [SawyerHood/windows9x#13]
I'm running into a persistent error where after maybe a few back and forth prompts with the "Dev" chat the output in the IFrame gets replaced with what looks like direct but incomplete output from the LLM response. 

Not sure what's happening here but my best guess would be not everything is getting loaded in possibly due to being too long or the LLM editing more than it should? It sometimes happens if I ask it to revert a change that didn't go well so could be linked to that.

This was happening on the public test and when running it locally.

![Screenshot_20240710-172532~2](https://github.com/SawyerHood/windows9x/assets/110859287/d59fbc04-4456-463a-887e-8ae560bb41c0)

**Comment by SawyerHood** [comment]
Thanks for the report again @snipeor! Let me dig into this.

**Comment by SawyerHood** [comment]
Do you mind emailing me the email you used to sign into windows9x.com? I can use that to look at logs and see what happened in this case. You can send it to kirbyhood@gmail.com

**Comment by SawyerHood** [comment]
Scratch that! I think I found you logs! It looks like the llm is not returning full html so it is returning only some of the changes which aren't valid on their own. Let me try to edit the prompt a bit! Thanks again for reporting

**Comment by snipeor** [comment]
> Scratch that! I think I found you logs! It looks like the llm is not returning full html so it is returning only some of the changes which aren't valid on their own. Let me try to edit the prompt a bit! Thanks again for reporting

No worries, it's the main bug I've found so far, otherwise seems to be working well.

**Comment by SawyerHood** [comment]
Just pushed a fix that should make this more fault tolerant! I'm going to close for now, but let me know and reopen if you run into it again. This also makes me realize that I should support history so it is easier to roll back changes. I'll add a task for me to do that (no ETA atm)
