### ISSUE TITLE
Next.js compatibility issues: Worker threads and Web APIs not fully supported

### ISSUE THREAD

**Issue by snipeor** [SawyerHood/windows9x#6]
## Description
When attempting to run the Windows9x project using Bun I'm encountering multiple errors related to unsupported features in worker threads and missing Web APIs.

## Environment
- Bun version: 1.1.17
- Next.js version: 14.2.4 (as specified in the project)
- Operating System: Linux Ubuntu 20.04 6 live server (VM on proxmox)

## Error Log
Key errors encountered:

1. Worker Thread Issues:
NotImplementedError: worker_threads.Worker option "stdout" is not yet implemented in Bun.
NotImplementedError: worker_threads.Worker option "stderr" is not yet implemented in Bun.
NotImplementedError: worker_threads.Worker option "resourceLimits" is not yet implemented in Bun.
2. Regular Expression Errors:
error: Invalid flag "r" in regular expression
error: Invalid flag "o" in regular expression
error: Invalid flag "b" in regular expression

## Steps to Reproduce
1. Clone the Windows9x repository
2. Set up the environment as per README instructions
3. Run it using `bun run dev`

## Expected Behavior
The Windows9x development server should start and run without these compatibility errors.

## Actual Behavior
The server starts but upon trying to create a new program nothing happens. The ? still works though as a way to edit "blank" apps though.

**Comment by SawyerHood** [comment]
Let me update the README. What version of `node` do you have installed run `node --version`. There is an implicit dependency since bun should run node when running dev.

**Comment by snipeor** [comment]
> node --version

turns out it wasnt installed but when I install it using apt-get (version v10.19.0) I can't run it anymore and get this error
/home/rob/windows9x/node_modules/next/dist/compiled/commander/index.js:1
(()=>{var t={81:t=>{"use strict";t.exports=require("child_process")},361:t=>{"use strict";t.exports=require("events")},147:t=>{"use strict";t.exports=require("fs")},17:t=>{"use strict";t.exports=require("path")},282:t=>{"use strict";t.exports=require("process")},161:(t,e,i)=>{const{InvalidArgumentError:n}=i(854);class Argument{constructor(t,e){this.description=e||"";this.variadic=false;this.parseArg=undefined;this.defaultValue=undefined;this.defaultValueDescription=undefined;this.argChoices=undefined;switch(t[0]){case"<":this.required=true;this._name=t.slice(1,-1);break;case"[":this.required=false;this._name=t.slice(1,-1);break;default:this.required=true;this._name=t;break}if(this._name.length>3&&this._name.slice(-3)==="..."){this.variadic=true;this._name=this._name.slice(0,-3)}}name(){return this._name}_concatValue(t,e){if(e===this.defaultValue||!Array.isArray(e)){return[t]}return e.concat(t)}default(t,e){this.defaultValue=t;this.defa

SyntaxError: Unexpected token ?
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at Module.mod.require (/home/rob/windows9x/node_modules/next/dist/server/require-hook.js:65:28)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/rob/windows9x/node_modules/next/dist/bin/next:7:20)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
error: script "dev" exited with code

**Comment by SawyerHood** [comment]
I just updated the README. Can you try to install v21 or greater?

**Comment by snipeor** [comment]
Fixed the issue thanks! I'm not sure why Ubuntu doesn't serve the latest version, maybe for stability reasons since im on the server build. Anyway I used https://nodejs.org/en/download/package-manager/current to help find a way to get the latest version.
