### ISSUE TITLE
Feature Request: Allow users to use their own Replicate API key for image generation

### ISSUE THREAD

**Issue by snipeor** [SawyerHood/windows9x#9]
### Description
Currently, the application doesn't provide a way for users to use their own Replicate API key for image generation - as far as I can see it looks like you're planning to load this in from supabase? 

### Proposed Solution
Implement a way for users to input and use their own Replicate API key for image generation tasks within the application. This could involve:

1. Adding a field in the .env file to input the Replicate API key
2. Securely storing the API key
3. Using the user's API key instead of a global key when making requests to Replicate

### Side Note
Hope this is useful feedback and I'm not missing anything obvious. I'm no coder (obviously) just tinker with these things and think the project is really cool, I was going to try and implement something myself with help from claude but what would take me hours would probably take you minutes.

**Comment by SawyerHood** [comment]
TY for the feedback! Right now if you add `REPLICATE_API_TOKEN` to the env file you can use your own! The repo is moving pretty fast right now (I'm working on getting a hosted version up), but I'm going to do another pass at the documentation soon to update this.

**Comment by SawyerHood** [comment]
Long story short my plan is to make it so it is much easier to run locally and you can choose which services you want to enable or not. I made an issue here https://github.com/SawyerHood/windows9x/issues/10

**Comment by snipeor** [comment]
Yeah I noticed as I grabbed the latest version last night a few things broke and rolled back to previous one. I figured you may just need more time like you say. Looking good so far and will definitely be letting others know about the hosted version!
